version: "3.9"
services:
  webapp:
    ports: 
      - 8080:80 #order is opposite from docker cli
    build:
      context: ./
      dockerfile: ./docker/nginx/Dockerfile
    image: docker_ws/nginx_ws_static:1.2
    environment: 
      WEB_DOCUMENT_ROOT: /usr/share/nginx/html
      PHP_FPM_HOST: php-fpm
      BASE_URL: /home
      

  php-fpm:
    image: php:7.4-fpm
    ports: 
      - 9000:9000
    volumes:
      - ./docker/php/etc/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf  
      - ./web/:/usr/share/nginx/html/